# Generated by Django 3.2.3 on 2021-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Mercedes', 'MERCEDES'), ('BMW', 'BMW'), ('Opel', 'OPEl'), ('Alfa Romeo', 'ALFA ROMEO'), ('Toyota', 'TOYOTA')], max_length=20)),
                ('brand_model', models.CharField(max_length=20)),
                ('condition_new', models.BooleanField()),
                ('condition_old', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('color', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=20)),
                ('miliege', models.IntegerField()),
            ],
        ),
    ]
