# Generated by Django 3.2.3 on 2021-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition_new',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition_old',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='miliege',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
