# Generated by Django 3.2.3 on 2021-06-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210601_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
