# Generated by Django 3.2.3 on 2021-06-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='miliege',
            field=models.IntegerField(),
        ),
    ]
