# Generated by Django 3.2.3 on 2021-06-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_miliege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='condition_new',
            new_name='condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='condition_old',
        ),
    ]
