# Generated by Django 3.2.3 on 2021-06-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210601_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
