# Generated by Django 3.2.3 on 2021-06-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210601_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='cars.imagealbum'),
        ),
    ]
