# Generated by Django 3.2.3 on 2021-06-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='cars.imagealbum'),
        ),
    ]
