# Generated by Django 3.2.3 on 2021-06-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='album',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
