# Generated by Django 3.2.3 on 2021-06-01 15:21

import cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20210601_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cars.models.get_image_filename, verbose_name='Image')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
