# Generated by Django 3.2.3 on 2021-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_car_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
